version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/flaskDD:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
    env_file:
      - .env
    environment:
      - FLASK_RUN_PORT=5000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    expose:
      - 8080


  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - flask
    ports:
      - "8080:80"



